# Generated by Django 2.0 on 2025-03-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='code',
            field=models.IntegerField(default=1000),
        ),
    ]
