name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate

    - name: Deploy to server
      env:
        SERVER_PASSWORD: ${{ secrets.PASS }}
      run: |
        sudo apt-get install -y sshpass
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@82.112.226.47 << 'EOF'
          cd ~/ZAPMAIL-
          git pull origin main
          source venv/bin/activate
          pm2 restart django-app || pm2 start python3 --name "django-app" -- manage.py runserver 0.0.0.0:8888
        EOF
